### ISSUE TITLE
CentOS el7 installaton

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/homer-snmp#1]
Hello,

I am having issues installing and running homer-snmp in CentOS el7.
Please see details and npm_debug [here](http://pastebin.com/JsuNwPFg)

**Comment by lmangani** [comment]
Hi @ishmaelen 
Does ` ` `npm install request --save` ` ` solve your issue?

**Comment by lmangani** [comment]
Extended ` ` `package.json` ` `with` ` `require` ` `

**Comment by ishmaelen** [comment]
Hello,

Now I get the following error (see below). Verified API login works using curl.

/usr/local/src/homer-snmp/hsnmp.js:18
jar.add(homercookie);
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/src/homer-snmp/hsnmp.js:18:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Debug-log:

15 verbose stack Error: homer-snmp@ start: `node hsnmp.js`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
15 verbose stack     at EventEmitter.emit (events.js:110:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
15 verbose stack     at ChildProcess.emit (events.js:110:17)
15 verbose stack     at maybeClose (child_process.js:1008:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by ishmaelen** [comment]
I think this will work (since request uses tough-cookie):
jar.setCookie(homercookie, 'http://localhomst/api/v1', function(error, cookie) {});
